# Generated by Django 4.2.1 on 2023-07-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('id_cuenta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='AreaEjerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.areatrabajo')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.trabajador')),
            ],
        ),
    ]
