# Generated by Django 4.2.3 on 2023-07-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='calificacion_promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
